### ISSUE TITLE
Usage?

### ISSUE THREAD

**Issue by casoetan** [Karnith/angular-revolution#6]
How do I make use of this. I've followed your instructions but...

<code>
SyntaxError: Unexpected end of input
    at Object.parse (native)
    at hasValuesDefined (http://localhost:3000/bower_components/angular-revolution/release/angular-revolution.js:63:37)
    at http://localhost:3000/bower_components/angular-revolution/release/angular-revolution.js:73:43
    at http://localhost:3000/bower_components/angular/angular.js:17918:31
    at completeOutstandingRequest (http://localhost:3000/bower_components/angular/angular.js:5552:10)
    at http://localhost:3000/bower_components/angular/angular.js:5829:7
</code>

Don't quite get this error.

**Comment by casoetan** [comment]
Fixed. Was me.

**Comment by Karnith** [comment]
Hi @casoetan, thanks for trying this module. For transparency to other users, could you please comment on what the issue was and how you fixed it? It could help other users if they encounter a similar issue... thanks again.
