### ISSUE TITLE
jsFileLocation

### ISSUE THREAD

**Issue by jojoaddison** [Karnith/angular-revolution#7]
Hello,

Is this the location to the rs-plugin/js/jquery.themepunch.revolution.js file?
How does angular-revolution find the rs-plugin?
How does angular-revolution initiate the rs-plugin?

Thanks for your kind response.

**Comment by Karnith** [comment]
Hi @jojoaddison 

the rs-plugin needs to be loaded before the angular directive is loaded. The file structure isn't important in this case.

this line:
https://github.com/Karnith/angular-revolution/blob/master/src/angular-revolution.js#L68

is what initiates the plugins method .revolution(options) that is available once the rs-plugin is loaded on the site, hence why the rs-plugin needs to be loaded before the directive.

hope this helps.

**Comment by jojoaddison** [comment]
Hi @Karnith 
Thanks for your kind response.
I've been able to successfully implement your directive.
Regards.
