### ISSUE TITLE
TypeError: dbg is undefined

### ISSUE THREAD

**Issue by ghost** [Karnith/angular-revolution#8]
All works well until you try to navigate to another page inside the angualr app.  The app returns TypeError: dbg is undefined and does not move to another page.  I can access those pages directly, and use the menu no problem, but any page that contains the angular revolution will not navigate off page and produces the above error.

**Comment by Karnith** [comment]
can you send me a link to look at? What version of angular are you using and how are you calling the rev slider init function?

**Comment by ghost** [comment]
I am working on it locally.  I am using v1.4.10 of angular.  I reference `$scope.slider = {` and the paramters from the set up info you have here, as well as 
`var app = angular.module('app', [
	'bootstrapLightbox',
	'ui.router', 'ui.bootstrap', 'flash', 'login', 'dashboard','rev.slider']);`

And forgive me if I am not answering this correctly.  Angular is very new to me - I am working with this https://github.com/ranjithprabhuk/Angular-Bootstrap-Dashboard and replacing the owl carousel with revolution

Like I said, the slider works perfectly - thank you for that!

**Comment by Karnith** [comment]
can you tell me where dbg comes from? it sounds like dbg is a variable that isn't being defined. If this is the case then your js code is being stopped on this error and not loading anything else in browser. If you can post the file that this is in a I can quickly look and might be able to determine what the issue is.

**Comment by ghost** [comment]
I've looked at other browsers, and this is only happening in Firefox.  Chrome, Safari, IE no issue ... DBG comes from the firebug debugger - turning it off, now it works fine in FF ... go figure that firebug would prevent an application from running ... I'm going to say this is a non issue.  Thanks for your time.

**Comment by Karnith** [comment]
OK, then with your conformation I'll close the ticket.

I used to use FireFox for development debugging, but since have moved to Chrome as it's tools seem to far surpass what firefox can do.

**Comment by ghost** [comment]
I've looked at other browsers, and this is only happening in Firefox.  Chrome, Safari, IE no issue ... DBG comes from the firebug debugger - turning it off, now it works fine in FF ... go figure that firebug would prevent an application from running ... I'm going to say this is a non issue.  Thanks for your time.

**Comment by ghost** [comment]
I'll be moving to chrome now that I see more and more issues with FF and it's plugins
